### ISSUE TITLE
Version badge

### ISSUE THREAD

**Issue by mereacre** [nqminds/edgesec#171]
Add the version number badge in README.md

**Comment by aloisklink** [comment]
There's not really a good way to do this.

We can use https://shields.io/category/version to pull the latest version from GitHub: https://github.com/nqminds/EDGESec/releases

Although we have no official releases, and the last prerelease is from [2022-05-13](https://github.com/nqminds/EDGESec/releases/tag/v0.9.9-alpha6-arm32)

**Comment by mereacre** [comment]
Shall we release the version 0.1.0?

**Comment by aloisklink** [comment]
We could also go to version `0.10.0` instead, since that's after `0.9.9`, which is what our pre-releases used.

**Comment by mereacre** [comment]
Sorry my mistake. I meant version 0.10.0
