### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by mereacre** [nqminds/edgesec#175]
Make to a new public repo.

**Comment by aloisklink** [comment]
I'm voting to close this.

Keeping the `debian/` folder in this repo has a few benefits:
  - We have the [`debian/copyright`](https://github.com/nqminds/edgesec/blob/main/debian/copyright) file, which has all the copyright/licenses for third-party code in this repo.
  - We have the [`debian/control`](https://github.com/nqminds/edgesec/blob/a23c9541e55d392a0a71e3d5297aa5dc7b98c246/debian/control#L5-L14) file, which has a list of [Build-Depends](https://github.com/nqminds/edgesec/blob/a23c9541e55d392a0a71e3d5297aa5dc7b98c246/debian/control#L5-L14) that are required to compile edgesec. This can be easily used to install dependencies on Debian systems (most common Linux OS) using [`mk-build-deps`](https://manpages.ubuntu.com/manpages/focal/man1/mk-build-deps.1.html)

**Comment by mereacre** [comment]
Good.
