### ISSUE TITLE
Remove the issuer_mac_addr from ticket structure

### ISSUE THREAD

**Issue by mereacre** [nqminds/edgesec#195]
The `issuer_mac_addr` field is not used in allocating the VLAN for the connecting device.

**Comment by mereacre** [comment]
See #202.

**Comment by aloisklink** [comment]
Closed by #202. Sorry, I wanted to show you the automatic closing feature of GitHub PRs (see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), but I accidentally wrote the wrong PR number!
