### ISSUE TITLE
Documentation missing a preset for TARGET=aarch64-linux-musl

### ISSUE THREAD

**Issue by katarapkokid** [nqminds/edgesec#209]
**Describe the bug**

Cross compiler settings as documented were not correct.

The objective was to compile the system for a RasberryPi Model 3B+, following the documentation
here: https://github.com/nqminds/edgesec/blob/main/README.md

**To Reproduce**
1. Edit /edgesec/config.mak to contain
```
# Raspberry Pi target
TARGET=aarch64-linux-musl

OUTPUT=/usr/local
MUSL_VER = 1.1.24
```

2. docker build
```
# docker build -t openwrt .
```

3. docker run 
``` 
# docker run --rm --volume "$PWD":/opt/EDGESec --workdir /opt/EDGESec openwrt cmake --preset openwrt/default
```
Produces errors. E.g.:
```
 The CMAKE_C_COMPILER:

    /usr/local/bin/arm-linux-musleabihf-gcc

  is not a full path to an existing compiler tool.
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_CXX_COMPILER:

    /usr/local/bin/arm-linux-musleabihf-g++

  is not a full path to an existing compiler tool.
```

4. Edit .cmake file
https://github.com/nqminds/edgesec/blob/main/CMakeModules/CMakeToolchains/arm-linux.cmake#L7

Comment out line 7 (missing from the docs).  It should look like this:

```
# set(CROSS_COMPILE_PREFIX /usr/local/bin/arm-linux-musleabihf-)
```

5. docker run command executes as expected

**Expected behaviour**

```
docker run --rm --volume "$PWD":/opt/EDGESec --workdir /opt/EDGESec openwrt cmake --preset openwrt/default
```
Should not produce errors relating to the cross compiler.

**Comment by aloisklink** [comment]
Thanks for reporting this @katarapkokid!

I've updated the docs in #215, and removed the old not working instructions.

I haven't added a generic preset for `aarch64-linux-musl`, but I've added a a preset called `openwrt-21.02.1/bcm27xx/bcm2710`. This preset automatically downloads the OpenWRT 21.02.1 SDK for bcm27xx/bcm2710 (aka the Raspberry Pi 3), and uses that to cross-compile.
