### ISSUE TITLE
src/ap/ap_service.c code-coverage is inconsistent

### ISSUE THREAD

**Issue by aloisklink** [nqminds/edgesec#394]
**Describe the bug**

Code-coverage for the `src/ap/ap_service.c` file is inconsistent.

For example, see https://github.com/nqminds/edgesec/pull/391#issuecomment-1381801377.
This PR doesn't change anything with our code, but somehow `src/ap/ap_service.c` had a code-coverage change. This is consistently happening with our PRs, which is a bit annoying, since we sometimes get a false-positive ❌ saying that the codecoverage got worse, but it turns out it's just `src/ap/ap_service.c`

**Expected behavior**

`src/ap/ap_service.c` always returns the same code-coverage.

**Additional context**

My gut feeling is that this means that there may be some sort of race-condition in https://github.com/nqminds/edgesec/blob/main/tests/ap/test_ap_service.c

However, Code coverage does have a guide on what to look into for [Unexpected Coverage Changes](https://docs.codecov.com/docs/unexpected-coverage-changes)

I checked the output of https://app.codecov.io/gh/nqminds/edgesec/commit/2fbaccfb91aebca7879676ce3744f81587372825 and https://app.codecov.io/gh/nqminds/edgesec/commit/072e3d8bca338ac5d834bd180bd2690dcf5d5e97 and it looks like the following lines are different:

```diff
--- 072e3d8bca338ac5d834bd180bd2690dcf5d5e97-code-cov	2023-01-27 12:30:08.577755316 +0000
+++ 2fbaccfb91aebca7879676ce3744f81587372825-code-cov	2023-01-27 12:30:29.421877663 +0000
@@ -8,20 +8,20 @@
 FN:168,find_ap_status
 FN:207,ap_sock_handler
 FN:248,register_ap_event
 FN:275,run_ap
 FN:316,close_ap
-FNDA:6,disconnect_ap_command
 FNDA:17,run_ap
-FNDA:6,check_sta_ap_command
 FNDA:12,denyacl_del_ap_command
-FNDA:17,close_ap
-FNDA:17,ping_ap_command
+FNDA:6,disconnect_ap_command
+FNDA:6,check_sta_ap_command
 FNDA:24,denyacl_ap_command
-FNDA:0,find_ap_status
 FNDA:17,register_ap_event
+FNDA:17,close_ap
+FNDA:0,find_ap_status
 FNDA:0,ap_sock_handler
+FNDA:17,ping_ap_command
 FNDA:12,denyacl_add_ap_command
 FNF:11
 FNH:9
 DA:34,17
 DA:35,17
```

They both seem to be calling the same functions to me, just in a different order, but I don't really know enough about the GCC code-coverage format to be sure.

**Comment by mereacre** [comment]
I don't see any way for a race condition because all of the process and file manipulation functions are mocked. Basically the test verifies the pre/post conditions of several if in the `run_ap` function.

**Comment by aloisklink** [comment]
> I don't see any way for a race condition because all of the process and file manipulation functions are mocked. Basically the test verifies the pre/post conditions of several if in the run_ap function.

Hmmmm, maybe there is some other test that also runs `src/ap/ap_service.c`? We should probably check this at some point.

**Comment by aloisklink** [comment]
Codecov is finally working and I've managed to find the lines that change coverage (tested as of commit https://github.com/nqminds/edgesec/commit/36ab29f708863cf46474b49c696123207784f2c0).

![lines that change coverage in `src/ap/ap_service.c`](https://user-images.githubusercontent.com/19716675/215800496-e76293c7-c92d-4e0e-afb4-78e2c23b631b.png)

It looks like sometimes in `run_ap()`, writing to `hconf->ctrl_interface_path` fails, which causes `ping_ap_command()` and `register_ap_event()` to fail.

This failure is probably due to `test_edgesec` and `test_supervisor`, because in `test_ap_service`:
  - `writeread_domain_data_str` is mocked so that it can never cause `ping_ap_command()` to fail: https://github.com/nqminds/edgesec/blob/89c5fe6ae09ca8068a9bde7d9bab5730888053ee/tests/ap/test_ap_service.c#L80-L110
  - `write_domain_data_s` is also mocked so that it can never fail: https://github.com/nqminds/edgesec/blob/89c5fe6ae09ca8068a9bde7d9bab5730888053ee/tests/ap/test_ap_service.c#L71-L78
