### ISSUE TITLE
Memory leak in `uci_lookup_section_ref()` function

### ISSUE THREAD

**Issue by aloisklink** [nqminds/edgesec#481]
It looks like the `uci_lookup_section_ref()` function has a memory leak.

`ti` is allocated with `calloc()`, but it's never `free()`-ed in the function, and as far as I'm aware, the pointer to `ti` is never passed out of this function.

https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L76-L83

**Comment by mereacre** [comment]
@aloisklink I had a look at the function and it seems that it has one memory leak and possibility to free a memory region which is not supposed to be freed by the `uwrt_lookup_package`.

Memory leek :)
https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L76 - when it allocates a `struct uci_type_list` causing a memory leak

Freeing a pointer which is not supposed to be freed:
https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L110

The pointer is freed here: https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L236

### Solution memory leak:
Add a `sys_free(ti)` here https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L107
and remove the below line (no idea why is the purpose of it)
https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L113

### Solution for freeing the wrong pointer:
Replace the below line with
https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L110
`ret = sys_strdup(s->e.name)`

**Comment by aloisklink** [comment]
> Memory leek :)

🥬🧅 :laughing:

(Unfortunately, the [Unicode® consortium rejected all three proposals for a leek emoji](https://unicode.org/emoji/emoji-requests.html), so instead I have to combine 🥬 and 🧅 :sob:)

> Solution memory leak

Your solution sounds good! Feel free to make a PR (although use `os_free` or just plain `free()` instead of `sys_free()`)!

> Freeing a pointer which is not supposed to be freed:

Actually, I don't think this is an issue. In the function `uci_lookup_section_ref()`, you don't need to `free()` the return value. Instead, you need to `free(*typestr)`;

E.g. this is how I believe the function needs to be used:

```c
char *malloced_memory = NULL;
const char *return_value = uci_lookup_section_ref(A, B, &malloced_memory);
free(malloced_memory); // only allocated if need be
```

I can make a PR that documents this behaviour.

**Comment by mereacre** [comment]
Feel free to make PR.

**Comment by aloisklink** [comment]
> and remove the below line (no idea why is the purpose of it)
> https://github.com/nqminds/edgesec/blob/a3bcd1bdc25771312de474b5549d8f4e5bcd80dd/src/utils/uci_wrt.c#L113

I've figured out the purpose of it (see PR #485 for a fix!)

Basically, if you call this function again with a different section that has the same `type` as a previous UCI section, it should print `@section_name[0]`, `@section_name[1]`, `@section_name[2]`, ...:

![image](https://user-images.githubusercontent.com/19716675/223194251-50be26b4-60d2-480d-9ba4-f3deb42f2030.png)

But since we weren't saving the increment, it was always doing `@section_name[0]`, `@section_name[0]`, `@section_name[0]` (0 each time!).
